### ISSUE TITLE
[MM-231] Feat: 읽을 사람 설정 바텀시트 수정 & 모임 스페이스/메인 홈 에러 해결

### ISSUE THREAD

**Issue by daindaind** [M0IM/FE-M#160]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

- 읽을 사람 설정하는 바텀시트 높이를 화면 스크린에 맞게 조정합니다.

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!

**기능 추가**
- [x] 실시간 피드 유저 상세 프로필 연결
- [x] 유저 상세 프로필의 후기 부분을 평점 누르면 스택으로 넘어가게끔 수정
- [x] 유저 상세 프로필에 유저 소개 추가하기 (후기 대신)

**스타일 조정**
- [x] 읽을 사람 설정하는 바텀시트 높이를 화면 스크린에 맞게 조정
- [x] 유저 후기 상세 화면 부분 스타일 수정 

**에러**
- [x] 갤럭시에서 바텀시트 내에 있는 input 포커스될 때, 포커스 아웃 시도할 시 키보드가 내려가지 않는 현상 해결
- [x] 모임 스페이스에서 유저 상세 프로필 확인 시, 크기가 작은 디바이스에서 후기가 잘리는 부분
- [x] MoimScheduleEvent 에러
- [x] 메인 화면 내 일정 추가하는 화면에서 키보드가 인풋 요소 가리는 버그
- [x] 모임 정보 수정 화면에서 키보드가 인풋 요소 가리는 버그
- [x] 메인 화면 모임 무슨 일이 일어나고 있나요 부분 더보기 로직 버그 (더 보여줄 내용이 없는데 버튼이 나타나는 경우?..일까요)

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

MM-231-feature/#231

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)

상세 프로필 스타일 조금 바꿈
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/8c06d85c-74e8-4884-9009-11c1e59f2444">

**Comment by dydals3440** [comment]
현재 유저 프로필 페이지, 유저 리뷰란 => 유저 개인 소개로 변경 
(모임 평가 클릭시 => 유저 리뷰로 변경 부탁드립니당)

그리고, 회의때 말한 수정사항들 반영 부탁드립니당
