### ISSUE TITLE
[MM-239] Feat: reject 사유 해결 &  모임 관련 버그 및 로직 수정

### ISSUE THREAD

**Issue by daindaind** [M0IM/FE-M#163]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

- reject 사유였던 것 중 하나인 성별, 생년월일, 지역/도시 정보 로그인시 요구하는 이유에 대한 설명에 대해 관해서 문구를 추가합니다.
- 내가 활동 중인 모임 불러올 때 모임장 / 관리자 / 모임원 / 전체 다르게 불러올 수 있도록 합니다.
- 모임 카테고리 관련해서 카테고리를 추가하거나, 문구를 변경합니다.
- 모임 스페이스 부분 연령 표시를 다르게 표시합니다.
- 가입 신청 상태 부분에서 시간이 지나면 일부는 사라질 수 있도록 변경합니다.
- 공지사항 읽을 사람 설정 관련한 API를 변경합니다.

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!

**API 변경이 필요한 작업**
- [ ] 내가 활동 중인 모임 API 변경 => 모임장 / 관리자 / 모임원 / 전체 (쿼리파람으로 다르게)
- [ ] 모임 관련 카테고리 API/DTO 변경 => 기타 카테고리 필요, 멀티 필터로로 찾을 수 있도록 수정
- [ ] 공지사항 읽을 사람 선택 시 전체 선택했음을 알 수 있도록 API 변경
- [ ] GLOBAL 타입의 Post는 모임 게시글에 포함되지 않도록 API 변경
- [ ] 가입 신청 상태 API 변경 => 완료된 것, 반려된 것 모두 일정 기간이 지나면 자동으로 사라지도록 변경

**로직 및 스타일 변경 작업**
- [x] 성별, 생년월일, 지역/도시 정보 로그인시 요구하는 이유에 대한 설명에 대해 관해서 문구를 추가
- [x] 1. 개인정보 동의에 문구 추가
- [x] 2. 입력 받는 회원가입 폼에, 문구를 작게 적음.
- [x] 모임 관련 카테고리 constants 변경 => IT/서울 에서 IT로 수정
- [x] 모임 찾기(모임 리스트) 화면 : 카테고리 한국어로 변경해서 보여주기
- [x] 모임 스페이스 (모임 홈) : 평균 연령 -> 연령대 표시로 수정
- [x] 모임 정보/게시글 수정 시, 변경 없이 저장하면 기존 이미지 들어오지 x
- [x] 모임 정보/게시글 수정 로직 변경 (API 호출 x)
- [x] 내가 활동 중인 모임이 없으면 없다고 알려주는 로직 변경
- [x] 유저 상세 리뷰 화면 style 수정

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

MM-239-feature/#239

**Comment by dydals3440** [comment]
모임 정보/게시글 수정 로직 변경 제 코드 참고하면 되긴하는뎅... 기존 useSingleImagePicker 부분에서 완전히, S3 도메인까지 호출해서, s3도메인/s3도메인/imageKey 이런식으로, s3도메인이 두번 호출되는 현상이 발생합니다...

```js
    const imageKey = uploadUri
      ? // uploadUri가 존재하면 사용.
        uploadUri
      : // uploadUri가 없는 경우 imageUri 사용.
        // imageUri가 도메인을 포함하면
        imageUri.includes(Config.AWS_S3_URL)
        ? // imageUri 도메인 제거
          imageUri.replace(Config.AWS_S3_URL, '')
        : // imageUri 제거
          imageUri;
```

일단 저는 이런식으로 자르긴했습니당... 
나중에 imageUri가 도메인을 포함하지 않게 하고 단순히 키네임만 받아서 아래와 같이 수정해도 좋아보입니다.
src에 Config.S3_URL/${imageUri} 이런식으로, 한번 머지후 수정하면 좋을 것 같습니당.
