### ISSUE TITLE
[MM-316] Style: UI/UX 어색한 부분 및 부족한 기능 추가

### ISSUE THREAD

**Issue by daindaind** [M0IM/FE-M#211]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

전체적으로 UI/UX가 어색하거나 이상한 부분을 수정합니다.

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!

**모임 리스트**
- [x] 가입한 모임 리스트 확인 스크롤 짧게 끊어지는 부분

**메인 화면**
- [x] 실시간 피드에 보이는 모임 좋아요 UI 없애기

**모임 스페이스**
- [x] 성별 X 표현 → 기타로 변경
- [x] 예정된 일정이 없다고 표시되지 않을 때가 있는 경우

**내 일정**
- [x] 색상 표시가 달력과 가까이 붙어있는 부분
- [x] 하단에서만 스크롤되지 않고, 전체적으로 스크롤되도록 변경
- [x] 내 일정 수정이 안되는 부분
- [x] 내 일정 새로고침이 불가한 부분

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

MM-316-feature/#316

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)

아래 노션 페이지의 [UI/UX가 어색한 부분]을 참고해주세요.
https://www.notion.so/11-8-5c4b6a1656144e49bc50a1e81b18a5a6?pvs=4

**Comment by dydals3440** [comment]
gradlew 버전 업데이트 해서, 머지 하나 했으니, 한번 풀땡기고 해결해주세용
