### ISSUE TITLE
[MM-63] Feat: 공용 컴포넌트 구현 & moim space 컴포넌트 구현

### ISSUE THREAD

**Issue by daindaind** [M0IM/FE-M#33]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

1. 공용 컴포넌트 구현
- [x] BottomSheet 컴포넌트
- [x] Schedule Box 컴포넌트
- [x] Floating Button  컴포넌트
- [x] Popover menu 컴포넌트
- [x] DatePickBottomSheet 컴포넌트

2. Moim Space 컴포넌트 구현
- [x] Schdule Preview Card 컴포넌트
- [ ] Detail Schedule 컴포넌트

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [x] 여러 화면에서 사용될 공용 컴포넌트를 제작합니다.
- [ ] Moim Space 화면에서 사용될 컴포넌트를 제작합니다.

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

MM-63-feature/#63

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)
BottomSheet 컴포넌트
<img width="346" alt="image" src="https://github.com/user-attachments/assets/e87592f8-a38f-47a7-840a-69b6b9302531">

Schedule Box 컴포넌트
<img width="400" alt="image" src="https://github.com/user-attachments/assets/7e2305e8-eac7-454c-a996-311f6c2f83e8">

Floating Button  컴포넌트
<img width="439" alt="image" src="https://github.com/user-attachments/assets/054b009e-6ae5-4418-b07e-b9b3321e6787">

Popover menu 컴포넌트
<img width="443" alt="image" src="https://github.com/user-attachments/assets/957abc93-5844-4f34-af50-e8c62402cd8e">

Schdule Preview Card 컴포넌트
<img width="440" alt="image" src="https://github.com/user-attachments/assets/1b804627-ff8c-4c1d-b889-e4002ff8ae24">

Detail Schedule 컴포넌트
<img width="430" alt="image" src="https://github.com/user-attachments/assets/9013c463-2771-45c2-808c-39be69e11390">
<img width="430" alt="image" src="https://github.com/user-attachments/assets/0905c97c-4e3f-451f-ad4f-74f4091c17e4">

**Comment by dydals3440** [comment]
달력이랑, 달력 밑에 있는 부분은 제가 만들겠습니당...
