### ISSUE TITLE
[MM-117] Feat: 모임 게시글 화면 UI 변경 및 API 연결

### ISSUE THREAD

**Issue by daindaind** [M0IM/FE-M#77]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

### 모임 게시글 UI 수정
- 게시글 작성 UI 변경 (1. 공지사항일 때/아닐 때 처리, 2. 카테고리 작성 화면에서 설정)
- 게시글 작성 시 [공지사항]일 때, 읽을 사람 설정하는 UI 추가
- 게시글 상세 화면에서 대댓글 작성 UI 수정

### API 연결
- 모임 게시글 카테고리별 리스트 조회
- 모임 상세 게시글 조회
- 댓글 처리 (신고, 차단, 채팅, 대댓글, 좋아요)
- 댓글 작성 및 불러오기
- 모임 게시글 작성
- 모임 게시글 수정 **(아직 API X)**

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [x] 게시글 작성 UI 변경
- [x] 게시글 작성 시 [공지사항]일 때, 읽을 사람 설정하는 UI 추가
- [x] 게시글 상세 화면에서 대댓글 작성 UI 수정
- [x] 모임 게시글 카테고리별 리스트 조회
- [x] 모임 상세 게시글 조회
- [ ] 댓글 신고하기 **(아직 API X)**
- [ ] 댓글 작성자 차단하기 **(아직 API X)**
- [x] 댓글 좋아요 
- [ ] 대댓글 신고 **(아직 API X)**
- [ ] 대댓글 작성자 차단하기 **(아직 API X)**
- [ ] 대댓글 좋아요 **(아직 API X)**
- [x] 댓글 작성 및 불러오기
- [x] 대댓글 작성
- [x] 모임 게시글 작성
- [ ] 모임 게시글 수정 **(아직 API X)**
- [x] 게시글 좋아요 
- [ ] 게시글 수정하기 **(아직 API X)**
- [ ] 게시글 작성자 차단하기 **(아직 API X)**
- [ ] 게시글 신고하기 **(아직 API X)**

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

MM-117-feature/#117

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)
<img width="312" alt="image" src="https://github.com/user-attachments/assets/ef959698-89ce-4ee7-b308-f1571dcb350c">
<img width="318" alt="image" src="https://github.com/user-attachments/assets/83e3e8d3-38c2-4c14-abfe-5e2fa5717eb7">
<img width="322" alt="image" src="https://github.com/user-attachments/assets/f141f81e-0f04-40bd-b632-f71d7df36c68">
<img width="321" alt="image" src="https://github.com/user-attachments/assets/305e4735-91e0-4aaa-863b-de89a54ce18d">
<img width="318" alt="image" src="https://github.com/user-attachments/assets/f64825b5-db44-4cfa-8c49-e76dc5b23fe2">

**Comment by dydals3440** [comment]
달립시다...
